# Generated by Django 5.1.5 on 2025-02-22 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_instructor'),
        ('users', '0002_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'user__role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='taught_courses', to='users.instructor'),
        ),
    ]
